### ISSUE TITLE
Unable to build Android project in Cordova 5.0.0

### ISSUE THREAD

**Issue by mattdsteele** [LouisT/cordova-useragent#1]
To reproduce:
- Install the latest Cordova (5.0.0) and create a project
- `cordova platform add android`
- `cordova plugin add https://github.com/LouisT/cordova-useragent`
- `cordova build android`

```
:compileDebugJava
C:\test\101\a\platforms\android\src\im\ltdev\cordova\UserAgent\UserAgent.java:21: error: cannot find symbol
               settings = webView.getSettings();
                                 ^
  symbol:   method getSettings()
  location: variable webView of type CordovaWebView
1 error
:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.
```

It looks like `CordovaWebView` is now an interface that doesn't include the `getSettings()` function. [Source](https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/CordovaWebView.java)

**Comment by davemackintosh** [comment]
+1 on this.

**Comment by delijati** [comment]
Yes it has changed. The only way to set it is currently https://github.com/apache/cordova-android/pull/162 `OverrideUserAgent` or `AppendUserAgent` but this is not sufficient for my needs. I need to set it from JS.

**Comment by peterzebird** [comment]
+1

**Comment by LouisT** [comment]
This should be fixed with pull request #2

**Comment by firescout** [comment]
I just had this issue.

My issue was the plugins was a older version.

the fix was to remove and add a updated copy of the plugin

**Comment by Varun-Krishna-P** [comment]
Workaround here
     // super.appView.getSettings().setBuiltInZoomControls(true);
     // super.appView.getSettings().setDefaultZoom(ZoomDensity.MEDIUM); 
     // super.appView.getSettings().setSupportZoom(true);
Instead use this
import android.webkit.WebView;
WebView webView = (WebView) appView.getEngine().getView();
        WebSettings settings = webView.getSettings();
        settings.setBuiltInZoomControls(true);
        settings.setDefaultZoom(ZoomDensity.MEDIUM);
        settings.setSupportZoom(true);
Thanks,

**Comment by HaiderSahib** [comment]
Thanks, it works for me but it was required to change ZoomDensity.MEDIUM to WebSettings.ZoomDensity.MEDIUM

**Comment by jmevangelist** [comment]
Thanks that worked for me as well.

**Comment by Sowjanyaprao** [comment]
This one worked - WebSettings settings = webView.getSettings();

How do we zoom image only instead of page?
