### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by PauloBronfox** [LouisT/cordova-useragent#3]
Hey,

is it planned to support iOS ?

Thanks

**Comment by LouisT** [comment]
I don't do iOS development; Adding it would be a bit of an issue because of this. If anyone creates a PR for iOS support I would be more than happy to merge it.

**Comment by PauloBronfox** [comment]
I've had a look to develop it but there is a limitation. You can change the user agent at "run time" on Android but you can't on iphone. You can change it only before instantiation of the webview so the plugin approach is not really usefull. 
Thanks anyway. It's great for android

**Comment by LouisT** [comment]
Close this since it's not possible.
